#services:
#    Kasko\Services\Marketing\InboudLeadRequestFilter:
#        class: Kasko\Http\Event\KernelRequestSubscriber
#        arguments:
#            $logger: '@logger'
#            $securityService: '@security.csrf.token_manager'
#            $templateDataProviders: ['@Kasko\Services\TemplateData\HtmlPageDataCompiler']