twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        company_phone: '(912) 614-5004'
        company_email: 'kas@kaskoconstruction.com'
